# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designer/inputwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InputDialog(object):
    def setupUi(self, InputDialog):
        InputDialog.setObjectName("InputDialog")
        InputDialog.resize(709, 334)
        self.error_label = QtWidgets.QLabel(InputDialog)
        self.error_label.setGeometry(QtCore.QRect(10, 289, 611, 31))
        self.error_label.setText("")
        self.error_label.setObjectName("error_label")
        self.horizontalLayoutWidget = QtWidgets.QWidget(InputDialog)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 711, 281))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_4 = QtWidgets.QFormLayout()
        self.formLayout_4.setObjectName("formLayout_4")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.input_txt = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.input_txt.setEnabled(True)
        self.input_txt.setObjectName("input_txt")
        self.formLayout_4.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.input_txt)
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.minbox = ScienDSpinBox(self.horizontalLayoutWidget)
        self.minbox.setEnabled(True)
        self.minbox.setDecimals(8)
        self.minbox.setMaximum(1000000000.0)
        self.minbox.setProperty("value", 0.0)
        self.minbox.setObjectName("minbox")
        self.formLayout_4.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.minbox)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.maxbox = ScienDSpinBox(self.horizontalLayoutWidget)
        self.maxbox.setEnabled(True)
        self.maxbox.setDecimals(8)
        self.maxbox.setMaximum(1000000000.0)
        self.maxbox.setProperty("value", 0.005)
        self.maxbox.setObjectName("maxbox")
        self.formLayout_4.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.maxbox)
        self.label_30 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_30.setObjectName("label_30")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_30)
        self.fs_box = ScienDSpinBox(self.horizontalLayoutWidget)
        self.fs_box.setEnabled(True)
        self.fs_box.setMinimum(0.01)
        self.fs_box.setMaximum(1000000000.0)
        self.fs_box.setProperty("value", 40000.0)
        self.fs_box.setObjectName("fs_box")
        self.formLayout_4.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.fs_box)
        self.label_62 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_62.setObjectName("label_62")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_62)
        self.dsh_box = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.dsh_box.setDecimals(0)
        self.dsh_box.setMinimum(0.0)
        self.dsh_box.setMaximum(100.0)
        self.dsh_box.setSingleStep(1.0)
        self.dsh_box.setProperty("value", 50.0)
        self.dsh_box.setObjectName("dsh_box")
        self.formLayout_4.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.dsh_box)
        self.label_63 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_63.setObjectName("label_63")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_63)
        self.dla_box = QtWidgets.QDoubleSpinBox(self.horizontalLayoutWidget)
        self.dla_box.setDecimals(0)
        self.dla_box.setMinimum(0.0)
        self.dla_box.setMaximum(100.0)
        self.dla_box.setSingleStep(1.0)
        self.dla_box.setProperty("value", 10.0)
        self.dla_box.setObjectName("dla_box")
        self.formLayout_4.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.dla_box)
        self.horizontalLayout.addLayout(self.formLayout_4)
        self.textBrowser = QtWidgets.QTextBrowser(self.horizontalLayoutWidget)
        self.textBrowser.setEnabled(True)
        self.textBrowser.setObjectName("textBrowser")
        self.horizontalLayout.addWidget(self.textBrowser)
        self.check_btn = QtWidgets.QPushButton(InputDialog)
        self.check_btn.setEnabled(True)
        self.check_btn.setGeometry(QtCore.QRect(630, 290, 71, 34))
        self.check_btn.setObjectName("check_btn")

        self.retranslateUi(InputDialog)
        QtCore.QMetaObject.connectSlotsByName(InputDialog)

    def retranslateUi(self, InputDialog):
        _translate = QtCore.QCoreApplication.translate
        InputDialog.setWindowTitle(_translate("InputDialog", "Dialog"))
        self.label_3.setText(_translate("InputDialog", "Entrada"))
        self.input_txt.setText(_translate("InputDialog", "cos(2*pi*1000*t)"))
        self.input_txt.setPlaceholderText(_translate("InputDialog", "Function expression"))
        self.label.setText(_translate("InputDialog", "Mínimo"))
        self.minbox.setSuffix(_translate("InputDialog", "s"))
        self.label_2.setText(_translate("InputDialog", "Máximo"))
        self.maxbox.setSuffix(_translate("InputDialog", "s"))
        self.label_30.setText(_translate("InputDialog", "fs"))
        self.fs_box.setSuffix(_translate("InputDialog", "Hz"))
        self.label_62.setText(_translate("InputDialog", "Duty (SH)"))
        self.dsh_box.setSuffix(_translate("InputDialog", "%"))
        self.label_63.setText(_translate("InputDialog", "Duty (Llave)"))
        self.dla_box.setSuffix(_translate("InputDialog", "%"))
        self.textBrowser.setHtml(_translate("InputDialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Noto Sans\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">AYUDA:</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">IMPULSO UNITARIO: delta(t) </span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">ESCALON: heaviside(t0, a)  </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-style:italic;\">(centrado en t0 y con valor 0&lt;a&lt;1 en t0)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">SENO: sin(t)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">COSENO: cos(t)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">EXPONENCIAL: exp(t)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">CUADRADA: square(t, D)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">DIENTE DE SIERRA: sawtooth(t, w) </span><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-style:italic;\">(con -1&lt;=w&lt;=1)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">SINUSOIDAL GAUSIANA: gausspulse(t, fc=1000, bw=0.5, bwr=-6, tpr=-60, retquad=False, retenv=False)</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">SEÑAL MODULADA FM: chirp(t, f0, t1, f1, method=\'linear\', phi=0, vertex_zero=True)</span></p></body></html>"))
        self.check_btn.setText(_translate("InputDialog", "Validar"))
from src.widgets.scientific_spinbox import ScienDSpinBox
